name: GPT-4 Pull Request Automation

on:
  push:
    branches: [ "main" ]
    
permissions:
  contents: write
  pull-requests: write
jobs:
  gpt-process:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai==0.28.0

      - name: Determine changed files
        id: changed_files
        run: |
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          echo "CHANGED_FILES=$CHANGED_FILES"
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Run GPT processor
        run: |
          python scripts/gpt_processor.py

        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CHANGED_FILES: ${{ env.CHANGED_FILES }}

      - name: Commit changes
        run: |
          # Only commit if there's something new
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git checkout -b gpt-automatic-updates
            git add .
            git commit -m "chore: Automated GPT-4 changes"
          else
            echo "No changes to commit."
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: gpt-automatic-updates
          base: main
          title: "Automated GPT-4 changes"
          body: "This pull request includes GPT-4-based updates."
          token: ${{ secrets.GITHUB_TOKEN }}
