name: GPT Doc Automation

on:
  push:
    branches: [ "**" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  gpt-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai==0.28.0

      - name: Determine changed files
        id: changes
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          echo "CHANGED_FILES=$CHANGED_FILES"
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Run GPT doc updater
        run: |
          python scripts/doc_updater.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CHANGED_FILES: ${{ env.CHANGED_FILES }}

      - name: Commit doc updates
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs
            git commit -m "chore: Update docs via GPT"
          else
            echo "No documentation changes."
          fi

      - name: Create or Update Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ github.ref_name }}
          title: "GPT-Docs: Automated Documentation Updates"
          body: "Documentation changes generated by GPT."
          update-existing-pr: true
